title: "Daru Anna Thomas"
description: "Assistant Professor | Electrical Engineer | Researcher"
theme: jekyll-theme-minimal

nav:
  - name: "Home"
    link: index.md
  - name: "About"
    link: about.md
  - name: "Experience"
    link: experience.md
  - name: "Projects"
    link: projects.md
  - name: "Publications"
    link: publications.md
  - name: "Responsibilities"
    link: responsibilities.md
  - name: "Subjects Taught"
    link: teaching.md
  - name: "Contact"
    link: contact.md

markdown: kramdown
show_downloads: false
